spring.application.name=JGitAnalyser

server.port=8080

spring.data.mongodb.uri=mongodb://localhost:27017/gitAnalyser
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=gitAnalyser


logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.mongodb.driver=INFO

#google api configuration
gemini.api-key=${GOOGLE_API_KEY}
gemini.model=gemini-3.6-flash
gemini.enabled=true


spring.banner.location=classpath:banner.txt